### ISSUE TITLE
Invalid in playsound command

### ISSUE THREAD

**Issue by suareal** [karnhao/HaoDiscordBot#12]
# แจ้งเตือนข้อผิดพลาด

## **เกี่ยวกับข้อผิดพลาด**<br>
แสดงข้อความเล่นเพลง ๒ รอบ

## **วิธีทำให้เกิดข้อผิดพลาดอีกครั้ง**
ขั้นตอนเป็นดังนี้:
๑. ใช้คำสั่ง //พรีส //เล่นเพลง 
๒. มีโอกาศที่จะแสดงข้อความ ๒ รอบ

## **คาดหวัง**
แสดงข้อความรอบเดียวตามปกติ

## อุปกรณ์

**อุปกรณ์ (กรุณาระบุให้ครบ):**
 - อุปกรณ์ : เครื่องจักรหนังสือ มืออาชีพ เอ็ม๑
 - ระบบปฏิบัติการ: เครื่องจักรระบบปฏิบัติการ ๑๒
 - โปรแกรมสำหรับท่องอินเทอรเน็ต  : แอปพลิเคชันบาดหมางกัน
 - รุ่น : ๑๐๘๗๐๓ (เอเอฟ๔๖อี๗เอ)

**Comment by karnhao** [comment]
แก้ให้แล้วครับ ขอบคุณที่รายงานครับผม
