### ISSUE TITLE
First running don't create configs directory

### ISSUE THREAD

**Issue by suareal** [karnhao/HaoDiscordBot#9]
ตอนเปิด bot ครั้งแรก ระบบจะไม่สร้างโฟลเดอร์ configs ให้
แล้วจะต้องสร้างโฟลเดอร์เอง

1. เปิด bot ครั้งแรกที่พึ่งโคลนมา
2. เจอ error

**Expected behavior**
ระบบจะสร้างโฟล์เดอร์ configs ให้เองเมื่อเปิด bot ครั้งแรก

**Desktop:**
 - OS: MacOS 11.0.2
 - Version Big Sur

**Additional context**
ขอให้แก้ไขด้วย

**Comment by karnhao** [comment]
Fixed!

**Comment by suareal** [comment]
Accept : แก้ไขเรียบร้อยแล้ว 民國 110 年 12 月 19 日
